### ISSUE TITLE
Values filtering in Advanced Search page cut off 

### ISSUE THREAD

**Issue by sheilabrennan** [omeka-s-themes/thedaily#10]
On the Advanced Search form, in Firefox PC, the selected terms are cut off within the form:  ![advancedsearchform-thedaily](https://cloud.githubusercontent.com/assets/741484/19659794/40e1d3dc-99fb-11e6-9a80-9238f37d7d7d.jpg)

**Comment by mebrett** [comment]
Happening for me on dropdowns in Advanced Search and Collecting plugin, on Chrome and Firefox for Mac. 
![screen shot 2016-10-25 at 1 16 44 pm](https://cloud.githubusercontent.com/assets/2314070/19697029/bb6d707c-9ab7-11e6-8586-904c5af686ea.png)

**Comment by mebrett** [comment]
@kimisgold

**Comment by sheilabrennan** [comment]
This looks fixed on a PC with Adv Search and with Megan's dropdown menus.

**Comment by mebrett** [comment]
Fixed, even on my very large monitor.
