### ISSUE TITLE
Last item on menu not visible on iPhoneSafari

### ISSUE THREAD

**Issue by mebrett** [omeka-s-themes/thedaily#11]
Because of the way that Safari displays pages on the iPhone, with the nav bar overlapping the content, the last item on the nav menu is covered - and thus inaccessible. 
![file_000](https://cloud.githubusercontent.com/assets/2314070/19730972/e246bba6-9b69-11e6-91a3-2f2052ee9326.png)

I checked on my iPhone 5 and Alyssa's iPhone 6.

**Comment by mebrett** [comment]
@kimisgold

**Comment by kimisgold** [comment]
Are you not able to scroll?

**Comment by mebrett** [comment]
That's the end of the scrolling - I can't scroll further, although I know there's another page on the nav below Mapping.

**Comment by kimisgold** [comment]
Okay, a fix should up.

**Comment by mebrett** [comment]
Perfect, thank you.
