### ISSUE TITLE
Test new gallery and slider plugins with youtube

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/thedaily#14]
I'm trying a new set of jquery plugins that offer support for more types of media to appear in a lightbox. Youtube is a priority, with HTML5 video and URL values as goals down the line. 

At the moment, i'm using lightGallery + lightSlider to display images and youtube video media in a slider and lightbox on the item/show view. All other attached media should appear as "Other Media" further down on the page.

This should be tested using the "light-plugins" branch.

**Comment by mebrett** [comment]
YouTube shows up in the lightbox - thumbnail is zoomed in but once you hit play it displays properly. 
Non-displayed media is indeed attached as "other media". Example: http://dev.omeka.org/mebrett/testomekas/s/austen/item/4511
