### ISSUE TITLE
404 page looks like it's trying to render the page twice

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-themes/thedaily#17]
The 404 page doesn't show a Not Found message, and is rendering very oddly.

UPDATE: a url like http://localhost/omekas/s/s2/page/no is fine, but http://localhost/omekas/s/s2/no shows the odd behavior. not sure if that's a problem or not.

**Comment by kimisgold** [comment]
I'm having trouble replicating this bug on my local installation as well as Megan's dev site. These are the URLs I'm using:

http://dev.omeka.org/mebrett/testomekas/s/austen/no
http://dev.omeka.org/mebrett/testomekas/s/austen/page/no

The url without "page" is definitely throwing an error that disrupts the rendering, but it doesn't seem to render the page twice like you initially reported.

**Comment by patrickmj** [comment]
I'll try to narrow down how to reproduce it. Seems like there are things afoot.

@mebrett what version is your testomekas on?

http://dev.omeka.org/mebrett/testomekas/s/test-site/no

gives

Fatal error: Call to a member function getRequest() on null in /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Controller/Plugin/Params.php on line 93 

That's different, but I don't know if it's related.

This might not be a thing to care about, as I'm not replicating the clicks that produced the original problem I noticed. If I'm only finding problems by futzing with urls directly, I don't think it's a priority.

**Comment by mebrett** [comment]
I was two commits behind - just pulled to the latest version of develop on Omeka S. Up to date on the master branch of thedaily
