### ISSUE TITLE
Showcase page bumps icons down

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-themes/thedaily#18]
On an item showcase page, after the first item the icons get out of alignment. 

![showcasethedaily](https://user-images.githubusercontent.com/153262/30596025-f34bf4a2-9d20-11e7-9aa0-1ed37179b978.png)

**Comment by zerocrates** [comment]
You mean using the showcase block? or is there a specific page I'm not remembering?

(also this is a test to see if these will start showing up in Slack)

**Comment by patrickmj** [comment]
yeah, block, not page.

(I see it on Slack)
