### ISSUE TITLE
Slider issue in Safari

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka-s-themes/thedaily#21]
Hello,

I get an issue using the image slider in Safari where image width seems to be fixed to 800px and causes a shift in image ratio.

See captures attached.
<img width="500" alt="capture d ecran 2018-12-20 a 10 16 47" src="https://user-images.githubusercontent.com/3284234/50275942-f7018200-0440-11e9-9475-e55227e110af.png">
<img width="500" alt="capture d ecran 2018-12-20 a 10 17 10" src="https://user-images.githubusercontent.com/3284234/50275959-05e83480-0441-11e9-9d1d-719e6e8d6963.png">

Here are some additional info:
Omeka-S version: 1.3.0
TheDaily version: 1.3.0 - FYI I already had the issue with previous versions of both Omeka S and this theme
Safari version: Version 12.0 (14606.1.36.1.9) with cleared cache
All modules disabled.

Thanks in advance and have a nice day

Laurent

**Comment by ManOnDaMoon** [comment]
I had some time to look further into the issue.

First additional info: the issue appears also on iOS devices using Safari.

I managed to fix it using the code changes in the following commit of my own fork:
https://github.com/omeka-s-themes/thedaily/commit/d6998dba45285cd842e78b3b2823f9a3c2770fdb

As I'm not confident in my CSS skills, even less using Sass, I'll let you have a look and include the changes if they are correct.

**Comment by zerocrates** [comment]
@kimisgold can we confirm the problem and/or the fix?

**Comment by kimisgold** [comment]
I confirmed the problem and the fix looks good.
