### ISSUE TITLE
Test new core page block styles

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/thedaily#29]
See omeka/omeka-s#1480. The Daily provides a few of its own custom block styles on top of the core styles. Test on `block-styles` branches of both The Daily and Omeka S.

**Comment by mebrett** [comment]
No issues as far as I can see. It looks a bit odd if you put an Item Showcase and an Item with Metadata next to each other, as the opaque bars double up, but that's more aesthetic and an unlikely use case 
<img width="553" alt="Screen Shot 2020-01-06 at 4 18 22 PM" src="https://user-images.githubusercontent.com/2314070/71849516-3b89ab00-30a0-11ea-9d08-71b8a209dd10.png">

**Comment by kimisgold** [comment]
Yup, gonna call this fine.

**Comment by kimisgold** [comment]
So apparently I hadn't actually pushed the changes to the `block-styles` branch on the theme. That should be fixed now—could you pull and take another look?

**Comment by mebrett** [comment]
Everything looks good.
