### ISSUE TITLE
Titles breaking awkwardly on Item Showcase and Media blocks

### ISSUE THREAD

**Issue by mebrett** [omeka-s-themes/thedaily#4]
Item showcase and Media blocks are breaking titles according to the width of the thumbnail and not by word: 
<img width="1218" alt="screen shot 2016-10-20 at 1 29 46 pm" src="https://cloud.githubusercontent.com/assets/2314070/19571058/97927aa8-96ca-11e6-9b0b-3580f74676bb.png"> 
(item showcase, thumbnail medium)

<img width="328" alt="screen shot 2016-10-20 at 1 39 28 pm" src="https://cloud.githubusercontent.com/assets/2314070/19571069/a5466d80-96ca-11e6-8ce2-d6ba8a45fd9b.png">
(media, thumbnail square)

**Comment by mebrett** [comment]
Also occurring on mobile: 
![img_3678](https://cloud.githubusercontent.com/assets/2314070/19576639/adedfacc-96e1-11e6-98d9-91a59a248123.jpg)

**Comment by zerocrates** [comment]
There's been a _lot_ of effort put into the themes to make them hold the titles to the width of the thumbnail. I'm not sure it should be having that much interior spacing though.

On mobile there's... a lot that's not so great there. It doesn't really have space to show 4 across probably.

**Comment by kimisgold** [comment]
Yeah, I think I overcompensated for instances where long file names would go on forever. This should be fixed, and mobile views should now cap out at 2 items per row.

**Comment by sheilabrennan** [comment]
This is fixed when resizing my screen in Firefox. @mebrett have you checked on your phone?
