### ISSUE TITLE
Test link and accent setting update

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/thedaily#41]
I noticed that a lot of the links in The Daily aren't obvious due to the scope that applies the accent background color. The change from https://github.com/omeka-s-themes/thedaily/commit/4ad61ddd61edc756ea81d2d09045d44f04f14882 should assist in that. I need to test that the following links have colored backgrounds:

* search results
* breadcrumbs
* linked values in metadata
* linked resource titles in browse views.

All of these links should change accordingly if the user sets a custom accent color in the theme settings.

![image](https://user-images.githubusercontent.com/606764/145886812-044ec84f-e86e-4df1-b906-102100a6ca5e.png)

These should be tested in the Chrome, Firefox, Safari, and Edge.

**Comment by katknow** [comment]
This works well (and looks really good!) in Chrome, Firefox, Safari, and Edge.
