### ISSUE TITLE
Test metadata display

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/thedaily#42]
The Daily's metadata property and value and alignment were previously wrapping to new lines poorly and spaced too closely together without a margin. [I've revised the styles to use flexbox.](https://github.com/omeka-s-themes/thedaily/commit/f93917bf7b8ce4610763321e71176a5ee0c38713)

Test that the property labels and values use a two column layout on desktop, multiple values wrap to a new line with a divider in the second column. There should be a margin between the property label and the first value. On mobile widths, the labels and values should sit together in a single column layout.

This should be tested in Chrome, Firefox, Safari, and Edge for desktop resolutions, and Safari for iOS on mobile.

**Comment by katknow** [comment]
This looks good to me! Tested on Chrome, Firefox, Safari, Edge and mobile Safari.
