### ISSUE TITLE
Test new lightgallery viewer

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/thedaily#43]
I've updated The Daily's media viewer to use lightgallery, a more actively developed gallery plugin from the same developer who built the previous viewer, lightslider. It should work mostly the same but needs to be tested for basic functionality:

* Supports common visual media attachments (.jpg,.gif, .png, Youtube video, mp4)
* Can be maximized to fullscreen.
* Users can pan and zoom still images.
* The "download" button links to the file source. It will download files where applicable, or go to the original Youtube link. 

This feature is on the `master` branch and should be tested on all major browsers for both desktop and mobile devices.

**Comment by katknow** [comment]
I'm freshly pulled and on the master branch, but I'm currently getting the following error on all front end media when I click through the thumbnail:

 Error
Cannot use object of type Omeka\Api\Representation\MediaRepresentation as array

Details:

Error: Cannot use object of type Omeka\Api\Representation\MediaRepresentation as array in /var/www/html/katknow/OmekaSTesting/themes/TheDaily/helper/LightGalleryOutput.php:23
Stack trace:
#0 [internal function]: OmekaTheme\Helper\LightGalleryOutput->__invoke(Array)
#1 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(396): call_user_func_array(Object(OmekaTheme\Helper\LightGalleryOutput), Array)
#2 /var/www/html/katknow/OmekaSTesting/themes/TheDaily/view/omeka/site/media/show.phtml(12): Laminas\View\Renderer\PhpRenderer->__call('LightGalleryOut...', Array)
#3 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/html/k...')
#4 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#5 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#6 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#7 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#8 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#9 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#10 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#11 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#12 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
#13 {main}

**Comment by kimisgold** [comment]
Good catch, I forgot to carry over some adjustments from the item show to the media show. It should be fixed when you pull again.

**Comment by katknow** [comment]
This works well on still images. Both YouTube videos (first screenshot) and mp4s (second screenshot) just embed without utilizing the viewer (movs don't appear to work at all, but as they are not in your above list not sure if they should or not):

![Screenshot 2022-02-16 at 15-47-14 Katherine Knowles Ben Ostermeier Global DH Symposium Presentation · Test 1-2-3 · Katie's ](https://user-images.githubusercontent.com/84726696/154354272-fe1f3872-c9f0-4749-b547-56acb6e52272.png)

![Screenshot 2022-02-16 at 15-46-54 Daph Vid · Test 1-2-3 · Katie's Omeka S Testing Site](https://user-images.githubusercontent.com/84726696/154354276-48d43440-b437-42bc-b5a3-590e4f1fb512.png)

**Comment by kimisgold** [comment]
I've just expanded the video types supported to include the following: 'flv', 'x-flv', 'mp4', 'm4v',
'webm', 'wmv', 'quicktime/mov', borrowing from the list that the Html5Media plugin for Omeka Classic uses. Your .mov should work after pulling.

**Comment by katknow** [comment]
After most recent pull, .mov is appearing but getting this above all videos: 

Notice: Undefined index: otherMedia in /var/www/html/katknow/OmekaSTesting/themes/TheDaily/helper/SortMedia.php on line 30

**Comment by kimisgold** [comment]
[Okay, I think I've fixed the check.](https://github.com/omeka-s-themes/thedaily/commit/8a7c124f715de42ea3bc3b2ac24cafa2e8a9f55b) Ready for another pull!

**Comment by katknow** [comment]
This definitely changed the video interface for ones I uploaded:
![Screenshot 2022-02-17 214019](https://user-images.githubusercontent.com/84726696/154607594-7ef7abbc-f530-45df-9a9f-8554d29a5822.png)

YouTube is still in its regular embed look:
![Screenshot 2022-02-17 at 21-40-56 Katherine Knowles Ben Ostermeier Global DH Symposium Presentation · Test 1-2-3 · Katie's ](https://user-images.githubusercontent.com/84726696/154607682-3bc33b11-81b8-47fc-9d3f-9d9c446e3b0a.png)

Also, for despite clearing cache & doing hard refresh I'm having trouble getting the changes to appear in Firefox (same as pic in earlier comment--can expand, but don't have download options etc. like I now do in other browsers).

**Comment by kimisgold** [comment]
This is technically as intended. I embedded the videos directly on the media's show page, thinking the lightgallery viewer would be excessive. I think the only thing lost is the direct download link, but I could provide that. Is it too jarring not to have the lightgallery viewer for this view?

**Comment by katknow** [comment]
Oh got it, sorry I thought the videos were also supposed to be in the lightgallery viewer. I don't think the interface is jarring, I took another look and I think what was off putting was that the videos are off-center while with the lightgallery viewer photos/docs etc. are center but I need to look closer and see if that's something that's adjustable on my end.

**Comment by kimisgold** [comment]
I think I can style these to look more consistent with the lightgallery viewer without actually using the viewer. I'll also provide a direct download link.

**Comment by kimisgold** [comment]
The media show view should now have a similar frame to the item show with lightgallery enabled. It should also have a download link in the top right corner.

**Comment by katknow** [comment]
@kimisgold I think this is good to go!
