### ISSUE TITLE
Test media viewer video track support

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/thedaily#44]
[This issue mirrors one for Big Picture for Omeka Classic](https://github.com/omeka/theme-bigpicture/issues/27) that introduces video track support in the media viewer.

Please test the following:

* Videos attached to items appear in the gallery and can play both as the only files and as part of a mixed set of file types.
* Subtitle files can be attached and work properly.
  * They should not appear in the "Other Files" listing.
   * Track and video files must all share the same base file name (ex: "video.mp4", "video.vtt")
   * Theme now supports the following values for track metadata:
       * Dublin Core: Type ("subtitles", "captions", etc)
        * Dublin Core: Language (the language code for the track)
        * Dublin Core: Title (the label for the track)
    * Multiple language tracks are supported. They still must share the same base file name as the video: the user differentiates between them using their Dublin Core metadata.

This feature is on the `master` branch and should be tested on all major browsers for both desktop and mobile devices.

**Comment by katknow** [comment]
I was able to test this with the smaller video file (it only has English subtitles), and at that level it definitely does work! Although, it does appear in the file listing: 

![image](https://user-images.githubusercontent.com/84726696/154981081-a550a4fb-b56d-4618-9304-294bce2faec5.png)

**Comment by kimisgold** [comment]
I meant to circle back to this. Could you link me to your example?

**Comment by katknow** [comment]
@kimisgold here is the link: http://dev.omeka.org/katknow/OmekaSTesting/s/test123/item/26945

**Comment by kimisgold** [comment]
Hmmm, I'm wondering if you need to pull again. It looks like mp4s and other non-mov video files aren't being recognized by the media viewer, and I whitelisted them as a recent change. Can you pull and try these again?

**Comment by katknow** [comment]
I've re-pulled/cleared cache/hard refreshed and I'm not seeing any changes.

**Comment by kimisgold** [comment]
Can you go into your site settings and make sure that the "Embed media on item pages" setting is checked?

**Comment by katknow** [comment]
That was it. Someday I'll remember to check that every time--so sorry!

**Comment by kimisgold** [comment]
No problem. Glad to see that setting is working as expected as well!

**Comment by kimisgold** [comment]
Checking before I close this: does everything check out with video tracks on both the item show and the media show?

**Comment by katknow** [comment]
@kimisgold to clarify, the media show page on the back end? If so, I don't see captions on the back end media page. However, I think it's fine on user side: http://dev.omeka.org/katknow/OmekaSTesting/s/test123/media/26946

**Comment by kimisgold** [comment]
Nope, just the front end within the theme.
