### ISSUE TITLE
Test media caption theme setting

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/thedaily#45]
In response to a [forum post asking for help with caption support in the media viewer](https://forum.omeka.org/t/add-image-caption-for-the-daily-theme/14639/7), I've added a theme setting for displaying captions, either the display title or description. Test that the appropriate metadata appears in the media viewer when the setting is configured.

This feature is on the `master` branch and should be tested on all major browsers for both desktop and mobile devices.

**Comment by katknow** [comment]
See error in #43

**Comment by katknow** [comment]
Just to clarify--this should be displaying the metadata specifically related to that media, not the item title/description?

**Comment by kimisgold** [comment]
Yes, that's correct.

**Comment by katknow** [comment]
This appears to be working on both desktop & mobile and across browsers for both Title and Description.
