### ISSUE TITLE
Test PDF support

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/thedaily#46]
Test that PDFs appear within the lightgallery, both standalone and alongside other visual media. [This is the same feature introduced in Center Row's lightgallery](https://github.com/omeka-s-themes/centerrow/issues/52), where PDFs appear in the lightgallery viewer alongside browser-supported images, youtube, and html5 videos.

This feature is on the `master` branch and should be tested on all major browsers for both desktop and mobile devices.

**Comment by sharonmleon** [comment]
Same results as with Center Row:

Testing on a Mac with FFX, Chrome, and Safari.

PDFs appear in the light gallery on all browsers.

With FFX and Chrome the PDF wrapper includes the zoom and download controls. In the light gallery interface there are zoom controls, but they don't work.

In Safari there are no PDF wrapper zoom controls or download, and in the light gallery zoom controls do not work. Download does work in the light gallery interface.

**Comment by kimisgold** [comment]
> In the light gallery interface there are zoom controls, but they don't work.

This is expected behavior: lightgallery disables zoom controls for video and pdf. It's theoretically lower opacity, but I may hide it altogether to eliminate ambiguity.

> In Safari there are no PDF wrapper zoom controls or download

This seems to be dependent on how the browser wants to handle PDF support. In Safari, I see this minimal overlay of controls.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/606764/161840327-eb66256b-59e4-4305-961a-a6902ab09d65.png">

**Comment by sharonmleon** [comment]
I must have missed them on Safari. Just not expecting them to be at the bottom. 

Same results for FFX and Chrome on Windows. No PDF wrapper controls for Edge.

**Comment by kimisgold** [comment]
The PDF controls wrapper for Edge seems to be resolution-dependent and external to anything the theme can do. Everything within its control seems to work as expected.
