### ISSUE TITLE
Test configurable page blocks

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/thedaily#47]
This is the theme-specific issue for omeka/omeka-s#1859. Please test this using the latest version of Omeka S on the `develop` branch.

The Daily now supports configurable resource page blocks. On a site's theme settings panel, select The Daily's "Configure resource pages" button. Test that blocks can be reordered, removed, and readded on the show views of items, media, and item sets. The Daily only has a single "Main" block region.

**Comment by katknow** [comment]
For the most part this is working as anticipated, but there is some weirdness going on with the text at the start of the item sets page (although it does reorder properly--was able to flip values and resource class):

![image](https://user-images.githubusercontent.com/84726696/191386705-13cfd7e1-c195-4e4a-89d1-4285576c17d9.png)

![image](https://user-images.githubusercontent.com/84726696/191386730-eaa1429a-1b8b-414e-add3-1902d9b5ca37.png)

**Comment by kimisgold** [comment]
Can you do a hard refresh?

**Comment by katknow** [comment]
Hard refreshed & cleared cache in multiple browsers and nothing changed.

**Comment by kimisgold** [comment]
I figured it out: I wasn't seeing this because I had metadata values long enough to take up the full width of the page. I've updated the problem style, hopefully that fixes it for you.

**Comment by katknow** [comment]
Yep, that fixed it! Should be good to go now.
