### ISSUE TITLE
Search overlay displaying at odd times

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/thedaily#49]
When you use the nav to switch pages, the search overlay appears, for what seems an undue amount of time (shouldn't be showing at all I think?), while the new page loads:

![thedaily-overlay](https://user-images.githubusercontent.com/28012148/217360678-6266b057-38ad-4559-a87f-5161e2af3512.gif)

**Comment by kimisgold** [comment]
It seems like some slow js, as the page assigns the "close" class to the search form on load. I've created a custom view for the daily to assign close there instead, which should prevent this from happening.

**Comment by zerocrates** [comment]
This is probably fine but if you want to avoid the markup override for easier maintainability, I would imagine you can make the overlay only visible when it has the class `open` rather than hiding it with class `closed`, which wouldn't require changed markup or have a hiding delay.

**Comment by kimisgold** [comment]
Good point. Just pushed an update with that approach.

**Comment by allanaaa** [comment]
This looks good now!
