### ISSUE TITLE
On IE, menu button is way off to the right

### ISSUE THREAD

**Issue by mebrett** [omeka-s-themes/thedaily#5]
Horizontal scroll bar required. It actually took me a good minute to realize it wasn't completely missing.

Issue is unique to IE.

I'm not sure if this has anything to do with it, but I also noticed that in Firefox and Chrome the logo/site title aligns to the left side of the header, while in IE it shows up on the right. 

![thedailyie2](https://cloud.githubusercontent.com/assets/2314070/19607050/4d891bda-9795-11e6-9daf-bb304b5ffca6.PNG)

**Comment by kimisgold** [comment]
IE fix should be in.

**Comment by sheilabrennan** [comment]
FIxed
