### ISSUE TITLE
Default-aligned block flow in nromal

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/thedaily#52]
This default-aligned media embed block between two floated blocks (from https://github.com/omeka/omeka-s/issues/2157) is actually incongruous with how all the other themes display it:

<img width="1522" alt="Screenshot 2024-03-04 at 11 04 12" src="https://github.com/omeka-s-themes/thedaily/assets/28012148/47d348d3-d807-4533-b213-afd38e4318d1">

And it appears to be because of the display:flex set (from https://github.com/omeka-s-themes/thedaily/issues/51) on the media-render.

I prefer it this way, since default blocks should flow nicely between their floats. But the other themes, because of the audio player width:100% and no display:flex, bump it down to a new line:

<img width="953" alt="Screenshot 2024-03-04 at 11 17 53" src="https://github.com/omeka-s-themes/thedaily/assets/28012148/63e6ac5b-3544-4ff5-9e81-fe0192200ff2">

<img width="1235" alt="Screenshot 2024-03-04 at 11 17 26" src="https://github.com/omeka-s-themes/thedaily/assets/28012148/fa6ba33f-44f7-4045-bfe1-e8f385c6f866">

So I would fix all the other themes, actually, and find another way to achieve this in The Daily - but they should all be consistent either way, so it's up to you.

**Comment by kimisgold** [comment]
Consistently getting the audio player to take up the full width between two floated blocks while also keeping its text content grouped seemed to be too tricky when I attempted it. It currently relies on default styling, which sets the `.media-render` container to `display: inline-block` to keep it grouped with its text content, and the `audio` component takes up the full width of its container.
