### ISSUE TITLE
Metadata Browse highlight extends far right on item page

### ISSUE THREAD

**Issue by mebrett** [omeka-s-themes/thedaily#6]
When viewing an item page, the 'see all items with this value' link's highlight doesn't stop at the end of the word (behavior for other links) but extends to the right margin of the text area. I wasn't sure if this was expected behavior or not.

![thedaily_metadatabrowse](https://cloud.githubusercontent.com/assets/2314070/19607158/efd71acc-9795-11e6-8b15-0589c13501c8.png)

Behavior is consistent across IE, Chrome, and Firefox

**Comment by sheilabrennan** [comment]
@kimisgold  This is still happening in IE.

**Comment by kimisgold** [comment]
I'm going to try floating the metadata browse links to the right. It decreases the vertical space a value takes up and should still provide separation between the metadata browse link and the link for a resource value.

**Comment by sheilabrennan** [comment]
Yay floating works in IE.
