### ISSUE TITLE
Highlighting in navigation menu 

### ISSUE THREAD

**Issue by alyssafahringer** [omeka-s-themes/thedaily#8]
In Chrome and Firefox, the highlighting is slightly off in the navigation menu for pages nested under other pages. 

![screen shot 2016-10-24 at 1 28 30 pm](https://cloud.githubusercontent.com/assets/8807816/19656508/487b829e-99ee-11e6-9e14-f26f35636738.png)

![screen shot 2016-10-24 at 1 28 41 pm](https://cloud.githubusercontent.com/assets/8807816/19656507/4878885a-99ee-11e6-8ba0-549eff03f9c9.png)

**Comment by sheilabrennan** [comment]
I found the same in FFX for PCs. Also, on the 3rd level of nesting of pages. the highlighting around the breadcrumb trail disappear. 
![nav-highlighting-daily](https://cloud.githubusercontent.com/assets/741484/19659457/03cccbce-99fa-11e6-846b-1a7f6bc7c9ee.jpg)

**Comment by kimisgold** [comment]
@sheilabrennan The highlight is for the submenu, and not for the breadcrumbs.

**Comment by sheilabrennan** [comment]
gottcha @kimisgold

**Comment by sheilabrennan** [comment]
The main issue appears to be fixed.
