### ISSUE TITLE
Display of advanced search

### ISSUE THREAD

**Issue by alyssafahringer** [omeka-s-themes/thedaily#9]
I'm not sure if this is an issue, but I wanted to see if the advanced search is supposed to be displaying this way, and if there is supposed to be a line underneath the creator field: 

![screen shot 2016-10-24 at 2 52 41 pm](https://cloud.githubusercontent.com/assets/8807816/19659344/9102cad0-99f9-11e6-8343-2ac4fc4e7ba8.png)

[In Firefox and Chrome - looking at [this page](http://dev.omeka.org/omeka-s/s/tinbox/item-set/11807)]

**Comment by kimisgold** [comment]
I had overlooked the item-set/show view, so no, it's definitely not supposed to look like this. However, the line under the creator field is correct, as it's there to separate multiple values for a single field: in this case, separating 'Sir Arthur Conan Doyle' and Omeka resource 'Arthur Ignatius Conan Doyle'.

**Comment by mebrett** [comment]
The Advanced Search link is now showing up under the Items heading, which is located below the Item Set metadata. The highlight is normally sized. If that's how it's supposed to look, then it is fixed. 

<img width="592" alt="screen shot 2016-10-26 at 10 30 01 am" src="https://cloud.githubusercontent.com/assets/2314070/19730119/305b4396-9b67-11e6-9e1e-0c330621ecd5.png">
